import React, { useContext, useState } from "react";
import Head from "next/head";
import classes from "../styles/Home.module.css";
import Button from "../components/UI/Button/Button";
import Product from "../components/Product/Product";
import { LatestCollection, VisitedCollection } from "../external-data";
import Auth from "../components/Auth/Auth";
import { useWeb3Context } from "../context/Web3Context";
import useCheckUser from "../hooks/useCheckUser";

const Home = () => {
  const { web3, connect, disconnect, token } = useWeb3Context();

  const [show, setShow] = useState(false);
  const openAuth = () => {
    setShow(true);
  };
  const closeAuth = () => {
    setShow(false);
  };

  return (
    <main className={classes.Container}>
      <Auth show={show} clicked={closeAuth} />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={classes.Hero}>
        <header className="Hide">
          <h1>Call To Action</h1>
        </header>
        <div className={classes.HeroContainer}>
          {/* this is fucking shit. */}
          <div className={classes.Cta}>
            {web3 ? (
              <Button onClick={disconnect}>Disconnect</Button>
            ) : (
              <Button onClick={connect}>Connect</Button>
            )}
          </div>
        </div>
      </section>

      {/* <section className={classes.Latest}>
        <div>
          <header className={classes.LatestHeader}>
            <h1>Latest Collection</h1>
          </header>
          <div className={classes.ProductList}>
            {LatestCollection.map((prod) => (
              <Product
                key={prod.id}
                title={prod.title}
                image={prod.image}
                price={prod.price}
              />
            ))}
          </div>
        </div>
      </section>

      <section className={classes.Latest}>
        <div>
          <header className={classes.LatestHeader}>
            <h1>Visited Products</h1>
          </header>
          <div className={classes.ProductList}>
            {VisitedCollection.map((prod) => (
              <Product
                key={prod.id}
                title={prod.title}
                image={prod.image}
                price={prod.price}
              />
            ))}
          </div>
        </div>
      </section> */}
    </main>
  );
};

export default Home;
